// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

// Rust kütüphanesi deaktive edildi - Python servisi kullanılıyor
// import 'frb_generated.dart';
// import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Hibrit servisindeki sınıfları kullan ve export et
import 'services/whisper_hybrid_service.dart';
export 'services/whisper_hybrid_service.dart' show TranscriptResult, TranscriptSegment, WhisperMode;

// Mock fonksiyonlar - gerçek implementasyon Python servisinde
Future<bool> initializeWhisper({required String modelPath}) async {
  // Python servisi kullanılıyor
  return true;
}

Future<TranscriptResult> transcribeVideoWithWhisper({
  required String modelPath,
  required String videoPath,
}) async {
  // Python servisi kullanılıyor
  throw UnimplementedError('Python servisi kullanılıyor');
}

Future<TranscriptResult> transcribeAudioWithWhisper({
  required String modelPath,
  required String audioPath,
}) async {
  // Python servisi kullanılıyor
  throw UnimplementedError('Python servisi kullanılıyor');
}
