// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6KRHoWXauLmXCR-ULvhYu9JYUavJENBQ',
    appId: '1:321895588705:web:ef2f5e625dda254e939b20',
    messagingSenderId: '321895588705',
    projectId: 'lumina-app-da3a6',
    authDomain: 'lumina-app-da3a6.firebaseapp.com',
    storageBucket: 'lumina-app-da3a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb183PcXVYfAXpaiWfzg8tOAu8xNV4tes',
    appId: '1:321895588705:android:9c1e1d3dff094ebc939b20',
    messagingSenderId: '321895588705',
    projectId: 'lumina-app-da3a6',
    storageBucket: 'lumina-app-da3a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAedyCOk6mTMNv1zDsShzi8h5dfkvZDiAg',
    appId: '1:321895588705:ios:0d67736c3ed9807a939b20',
    messagingSenderId: '321895588705',
    projectId: 'lumina-app-da3a6',
    storageBucket: 'lumina-app-da3a6.firebasestorage.app',
    iosBundleId: 'com.example.lumina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAedyCOk6mTMNv1zDsShzi8h5dfkvZDiAg',
    appId: '1:321895588705:ios:0d67736c3ed9807a939b20',
    messagingSenderId: '321895588705',
    projectId: 'lumina-app-da3a6',
    storageBucket: 'lumina-app-da3a6.firebasestorage.app',
    iosBundleId: 'com.example.lumina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6KRHoWXauLmXCR-ULvhYu9JYUavJENBQ',
    appId: '1:321895588705:web:b7d2a9b3dcbd7de7939b20',
    messagingSenderId: '321895588705',
    projectId: 'lumina-app-da3a6',
    authDomain: 'lumina-app-da3a6.firebaseapp.com',
    storageBucket: 'lumina-app-da3a6.firebasestorage.app',
  );
}
