// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:lumina/services/firebase_config_service.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // GÜVENLİ: Firebase konfigürasyonu .env dosyasından okunuyor
  static FirebaseOptions get web {
    try {
      return FirebaseConfigService.getFirebaseOptions('web');
    } catch (e) {
      throw Exception('Firebase Web konfigürasyonu yüklenemedi: $e');
    }
  }

  static FirebaseOptions get android {
    try {
      return FirebaseConfigService.getFirebaseOptions('android');
    } catch (e) {
      throw Exception('Firebase Android konfigürasyonu yüklenemedi: $e');
    }
  }

  static FirebaseOptions get ios {
    try {
      return FirebaseConfigService.getFirebaseOptions('ios');
    } catch (e) {
      throw Exception('Firebase iOS konfigürasyonu yüklenemedi: $e');
    }
  }

  static FirebaseOptions get macos {
    try {
      return FirebaseConfigService.getFirebaseOptions('macos');
    } catch (e) {
      throw Exception('Firebase macOS konfigürasyonu yüklenemedi: $e');
    }
  }

  static FirebaseOptions get windows {
    try {
      return FirebaseConfigService.getFirebaseOptions('windows');
    } catch (e) {
      throw Exception('Firebase Windows konfigürasyonu yüklenemedi: $e');
    }
  }
}
