// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RsWhisperGpt
    extends
        BaseEntrypoint<RsWhisperGptApi, RsWhisperGptApiImpl, RsWhisperGptWire> {
  @internal
  static final instance = RsWhisperGpt._();

  RsWhisperGpt._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RsWhisperGptApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RsWhisperGptApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RsWhisperGptApiImpl, RsWhisperGptWire>
  get apiImplConstructor => RsWhisperGptApiImpl.new;

  @override
  WireConstructor<RsWhisperGptWire> get wireConstructor =>
      RsWhisperGptWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 19096293;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rs_whisper_gpt',
        ioDirectory: 'rs_whisper_gpt/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RsWhisperGptApi extends BaseApi {
  Future<bool> crateApiInitializeWhisper({required String modelPath});

  Future<TranscriptResult> crateApiTranscribeAudioWithWhisper({
    required String modelPath,
    required String audioPath,
  });

  Future<TranscriptResult> crateApiTranscribeVideoWithWhisper({
    required String modelPath,
    required String videoPath,
  });
}

class RsWhisperGptApiImpl extends RsWhisperGptApiImplPlatform
    implements RsWhisperGptApi {
  RsWhisperGptApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiInitializeWhisper({required String modelPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitializeWhisperConstMeta,
        argValues: [modelPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitializeWhisperConstMeta => const TaskConstMeta(
    debugName: "initialize_whisper",
    argNames: ["modelPath"],
  );

  @override
  Future<TranscriptResult> crateApiTranscribeAudioWithWhisper({
    required String modelPath,
    required String audioPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          sse_encode_String(audioPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transcript_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTranscribeAudioWithWhisperConstMeta,
        argValues: [modelPath, audioPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranscribeAudioWithWhisperConstMeta =>
      const TaskConstMeta(
        debugName: "transcribe_audio_with_whisper",
        argNames: ["modelPath", "audioPath"],
      );

  @override
  Future<TranscriptResult> crateApiTranscribeVideoWithWhisper({
    required String modelPath,
    required String videoPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          sse_encode_String(videoPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transcript_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTranscribeVideoWithWhisperConstMeta,
        argValues: [modelPath, videoPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranscribeVideoWithWhisperConstMeta =>
      const TaskConstMeta(
        debugName: "transcribe_video_with_whisper",
        argNames: ["modelPath", "videoPath"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TranscriptSegment> dco_decode_list_transcript_segment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_transcript_segment).toList();
  }

  @protected
  TranscriptResult dco_decode_transcript_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TranscriptResult(
      segments: dco_decode_list_transcript_segment(arr[0]),
      fullText: dco_decode_String(arr[1]),
      language: dco_decode_String(arr[2]),
      duration: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  TranscriptSegment dco_decode_transcript_segment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TranscriptSegment(
      start: dco_decode_f_64(arr[0]),
      end: dco_decode_f_64(arr[1]),
      text: dco_decode_String(arr[2]),
      confidence: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TranscriptSegment> sse_decode_list_transcript_segment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TranscriptSegment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transcript_segment(deserializer));
    }
    return ans_;
  }

  @protected
  TranscriptResult sse_decode_transcript_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_segments = sse_decode_list_transcript_segment(deserializer);
    var var_fullText = sse_decode_String(deserializer);
    var var_language = sse_decode_String(deserializer);
    var var_duration = sse_decode_f_64(deserializer);
    return TranscriptResult(
      segments: var_segments,
      fullText: var_fullText,
      language: var_language,
      duration: var_duration,
    );
  }

  @protected
  TranscriptSegment sse_decode_transcript_segment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_start = sse_decode_f_64(deserializer);
    var var_end = sse_decode_f_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_confidence = sse_decode_f_32(deserializer);
    return TranscriptSegment(
      start: var_start,
      end: var_end,
      text: var_text,
      confidence: var_confidence,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_transcript_segment(
    List<TranscriptSegment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transcript_segment(item, serializer);
    }
  }

  @protected
  void sse_encode_transcript_result(
    TranscriptResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_transcript_segment(self.segments, serializer);
    sse_encode_String(self.fullText, serializer);
    sse_encode_String(self.language, serializer);
    sse_encode_f_64(self.duration, serializer);
  }

  @protected
  void sse_encode_transcript_segment(
    TranscriptSegment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.start, serializer);
    sse_encode_f_64(self.end, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_f_32(self.confidence, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
